version: 1
disable_existing_loggers: False

formatters:
  standard:
    format: '%(asctime)s [%(levelname)s] %(name)s: %(message)s'

handlers:
  console:
    level: DEBUG
    formatter: standard
    class: logging.StreamHandler
  file:
    level: INFO
    formatter: standard
    class: logging.FileHandler
    filename: logs/log.log
    mode: a

loggers:
  '':
    handlers: [console, file]
    level: INFO
    propagate: True
  uvicorn:
    handlers: [console, file]
    level: INFO
    propagate: False
  sqlalchemy:
    handlers: [console, file]
    level: WARNING
    propagate: False